"use client";

import { useMemo, useState } from "react";
import { BookOpen, Bookmark, ExternalLink, Filter, Search, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";

const sources=[
 {id:"SC-2017-377",title:"TRF Limited v. Energo Engineering Projects Ltd.",citation:"(2017) 8 SCC 377",type:"Supreme Court judgment",year:2017,relevance:99,summary:"An ineligible arbitrator cannot nominate another arbitrator when the statutory bar applies."},
 {id:"SC-2020-760",title:"Perkins Eastman Architects DPC v. HSCC (India) Ltd.",citation:"(2020) 20 SCC 760",type:"Supreme Court judgment",year:2020,relevance:97,summary:"Unilateral appointment mechanisms can be tested against independence and impartiality requirements."},
 {id:"ACT-1872-27",title:"Indian Contract Act, 1872 — Section 27",citation:"Section 27",type:"Statutory provision",year:1872,relevance:93,summary:"Agreements in restraint of trade are generally void subject to recognized exceptions."},
];
export default function LawyerLegalResearchPage(){
 const [q,setQ]=useState("unilateral arbitrator appointment"); const [saved,setSaved]=useState<string[]>([]); const [ran,setRan]=useState(false);
 const results=useMemo(()=>sources.filter(s=>`${s.title} ${s.summary} ${s.citation}`.toLowerCase().includes(q.toLowerCase().split(' ')[0])),[q]);
 return <div className="space-y-8 py-4"><div><Badge variant="violet">Research workspace</Badge><h1 className="mt-2 font-serif text-4xl font-bold">Legal Research</h1><p className="mt-2 text-sm text-[var(--text-secondary)]">Search judgments, statutory provisions, citations, and save authorities against active matters.</p></div>
 <Card variant="glass" className="p-5"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 h-4 w-4 text-[var(--accent-blue)]"/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full rounded-xl border border-[var(--input-border)] bg-[var(--input-bg)] py-3 pl-11 pr-4 text-sm" placeholder="Search cases, sections, citations, legal issues..."/></div><Button onClick={()=>setRan(true)}><Search className="mr-2 h-4 w-4"/>Search</Button><Button variant="outline"><Filter className="mr-2 h-4 w-4"/>Filters</Button></div>{ran&&<div className="mt-4 flex items-center gap-2 text-xs text-emerald-400"><Sparkles className="h-4 w-4"/>Research pass complete · {results.length} matching sources in the demo corpus</div>}</Card>
 <div className="grid gap-6 lg:grid-cols-[1fr_.32fr]"><div className="space-y-4">{results.map(s=><Card key={s.id} variant="glass" className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="gold" size="sm">{s.citation}</Badge><Badge variant="blue" size="sm">{s.type}</Badge></div><h2 className="mt-2 font-serif text-lg font-bold">{s.title}</h2><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">{s.summary}</p></div><span className="rounded-lg bg-emerald-500/10 px-2 py-1 text-[10px] font-bold text-emerald-400">{s.relevance}% match</span></div><div className="mt-4 flex gap-2 border-t border-[var(--border-color)] pt-4"><Button variant="outline" size="sm"><ExternalLink className="mr-1.5 h-3.5 w-3.5"/>Open source</Button><Button variant="outline" size="sm" onClick={()=>setSaved(v=>v.includes(s.id)?v.filter(x=>x!==s.id):[...v,s.id])}><Bookmark className="mr-1.5 h-3.5 w-3.5"/>{saved.includes(s.id)?"Saved":"Save"}</Button></div></Card>)}{results.length===0&&<Card variant="glass" className="p-10 text-center"><BookOpen className="mx-auto h-8 w-8 text-[var(--text-muted)]"/><p className="mt-3 text-sm">No demo sources matched this query. Connect the RAG/API service to search the full corpus.</p></Card>}</div>
 <Card variant="glass" className="h-fit p-5"><h3 className="font-serif font-bold">Research workspace</h3><div className="mt-4 space-y-2 text-xs"><div className="rounded-xl bg-[var(--bg-card)] p-3">Saved authorities <b className="float-right">{saved.length}</b></div><div className="rounded-xl bg-[var(--bg-card)] p-3">Citation format <b className="float-right">SCC</b></div><div className="rounded-xl bg-[var(--bg-card)] p-3">Current matter <b className="float-right">Apex-101</b></div></div><div className="mt-5 rounded-xl border border-purple-500/20 bg-purple-500/5 p-4"><p className="text-[10px] uppercase tracking-wider text-purple-300">AI research assistant</p><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">Ask a focused legal question and the future RAG service can return authorities with citations and source metadata.</p></div></Card></div></div>
}
