"use client";

import { useState } from "react";
import { ArrowRight, BookOpen, FileText, Gavel, Lightbulb, Scale, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";

const cases=[
 {id:"case-101",title:"M/s Apex Infrastructure vs. Union of India",court:"Supreme Court of India",issue:"Arbitrator appointment under Section 11",facts:["Contract contains unilateral appointment clause","Respondent disputes independence of proposed arbitrator","Petitioner seeks appointment by court"]},
 {id:"case-102",title:"Sharma Land Holdings vs. State of Delhi",court:"Delhi High Court",issue:"Possession and transfer of property",facts:["Continuous possession is disputed","Registered transfer documents are under review","Notice response is pending"]}
];
export default function LawyerCaseIntelligencePage(){
 const [selected,setSelected]=useState(cases[0]); const [run,setRun]=useState(false);
 return <div className="space-y-8 py-4"><div><Badge variant="gold">AI case workspace</Badge><h1 className="mt-2 font-serif text-4xl font-bold">Case Intelligence</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--text-secondary)]">Turn a selected matter into structured facts, legal issues, relevant law, precedents, and an AI-ready research brief.</p></div>
 <div className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><Card variant="glass" className="p-4"><p className="workspace-label mb-3">Select matter</p>{cases.map(c=><button key={c.id} onClick={()=>{setSelected(c);setRun(false)}} className={`mb-2 w-full rounded-xl border p-4 text-left ${selected.id===c.id?'border-[var(--accent-gold)] bg-[var(--accent-gold)]/8':'border-[var(--border-color)] bg-[var(--bg-card)]'}`}><p className="text-sm font-semibold">{c.title}</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">{c.court}</p></button>)}<Button className="mt-3 w-full" onClick={()=>setRun(true)}><Sparkles className="mr-2 h-4 w-4"/>Run intelligence pass</Button></Card>
 <div className="space-y-4"><Card variant="glass" className="p-6"><div className="flex items-start justify-between gap-4"><div><Badge variant="blue">{selected.id}</Badge><h2 className="mt-2 font-serif text-2xl font-bold">{selected.title}</h2><p className="mt-1 text-xs text-[var(--text-secondary)]">{selected.court}</p></div><Scale className="h-7 w-7 text-[var(--accent-gold)]"/></div><div className="mt-5 rounded-xl border border-[var(--border-color)] bg-[var(--bg-card)] p-4"><p className="text-[10px] uppercase tracking-wider text-[var(--text-muted)]">Primary legal issue</p><p className="mt-1 text-sm font-semibold">{selected.issue}</p></div></Card>
 <div className="grid gap-4 md:grid-cols-2"><Card variant="glass" className="p-5"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-blue-400"/><h3 className="font-serif font-bold">Facts extracted</h3></div><ul className="mt-4 space-y-2">{selected.facts.map(f=><li key={f} className="text-xs leading-5 text-[var(--text-secondary)]">• {f}</li>)}</ul></Card><Card variant="glass" className="p-5"><div className="flex items-center gap-2"><Gavel className="h-4 w-4 text-purple-300"/><h3 className="font-serif font-bold">Relevant law</h3></div><div className="mt-4 space-y-2 text-xs"><p className="rounded-lg bg-[var(--bg-card)] p-3">Arbitration & Conciliation Act, Section 11</p><p className="rounded-lg bg-[var(--bg-card)] p-3">Section 12(5) + Seventh Schedule</p><p className="rounded-lg bg-[var(--bg-card)] p-3">Principles of independence</p></div></Card></div>
 <Card variant="glass" className="p-5"><div className="flex items-center gap-2"><BookOpen className="h-4 w-4 text-[var(--accent-gold)]"/><h3 className="font-serif font-bold">Relevant precedents</h3></div><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-card)] p-4"><p className="text-xs font-bold">TRF Limited v. Energo</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">(2017) 8 SCC 377</p></div><div className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-card)] p-4"><p className="text-xs font-bold">Perkins Eastman v. HSCC</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">(2020) 20 SCC 760</p></div></div></Card>
 {run&&<Card variant="glass" className="border-emerald-500/20 bg-emerald-500/5 p-5"><div className="flex gap-3"><Lightbulb className="h-5 w-5 shrink-0 text-emerald-400"/><div><h3 className="font-serif font-bold">AI research brief generated</h3><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">The frontend has assembled a structured brief. Connect your RAG service here to return source-grounded analysis, judge/court metadata, exceptions, and citations.</p><Button variant="outline" size="sm" className="mt-3"><ArrowRight className="mr-1.5 h-3.5 w-3.5"/>Send to Legal Research</Button></div></div></Card>}
 </div></div></div>
}
