"use client";

import { useEffect, useState } from "react";
import { Bell, Briefcase, CheckCircle2, Clock3, FileCheck, Lock, Palette, Save, Shield, UserRound, type LucideIcon } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { LogoutButton } from "@/components/auth/LogoutButton";
import { getSession, updateSession, type SessionUser } from "@/lib/auth";
import { getLegalTheme, setLegalTheme, ThemeIcon } from "@/components/ui/ThemeToggle";

type Role = "CITIZEN" | "LAWYER";
type Theme = "light" | "dark" | "system";

const citizenPrefs = ["case-updates","hearing-reminders","documents","judgments","research-alerts","communications"];
const lawyerPrefs = ["client-cases","client-messages","court-updates","document-uploads","research-alerts","billing-alerts"];
const labels: Record<string,string> = {"case-updates":"Case status updates","hearing-reminders":"Hearing reminders",documents:"Document processing",judgments:"Relevant judgments","research-alerts":"Research alerts",communications:"Lawyer communications","client-cases":"New client cases","client-messages":"Client messages","court-updates":"Court updates","document-uploads":"Client document uploads","billing-alerts":"Billing alerts"};

export function SettingsPage({ role }: { role: Role }) {
 const [tab,setTab]=useState("profile"); const [user,setUser]=useState<SessionUser|null>(null); const [theme,setTheme]=useState<Theme>("dark"); const [saved,setSaved]=useState(false);
 const [channels,setChannels]=useState({email:true,push:true,inapp:true}); const [prefs,setPrefs]=useState<Record<string,boolean>>({});
 useEffect(()=>{ const u=getSession(); setUser(u); setTheme(getLegalTheme()); const stored=localStorage.getItem(`legalai-${role.toLowerCase()}-notifications`); if(stored) setChannels(JSON.parse(stored).channels||channels),setPrefs(JSON.parse(stored).prefs||{}); else setPrefs(Object.fromEntries((role==='LAWYER'?lawyerPrefs:citizenPrefs).map(k=>[k,true]))); const onTheme=()=>setTheme(getLegalTheme()); window.addEventListener('legalai-theme-change',onTheme); return()=>window.removeEventListener('legalai-theme-change',onTheme); },[role]);
 const save=()=>{ localStorage.setItem(`legalai-${role.toLowerCase()}-notifications`,JSON.stringify({channels,prefs})); setSaved(true); window.setTimeout(()=>setSaved(false),1800); };
 const changeTheme=(value:Theme)=>{setTheme(value);setLegalTheme(value);};
 const isLawyer=role==='LAWYER';
 const tabs=[{id:'profile',label:'Profile',icon:UserRound},{id:'notifications',label:'Notifications',icon:Bell},{id:'appearance',label:'Appearance',icon:Palette},{id:'security',label:'Security',icon:Lock},...(isLawyer?[{id:'verification',label:'Verification',icon:Shield}]:[])];
 return <div className="space-y-8 py-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><Badge variant={isLawyer?'violet':'blue'}>{isLawyer?'Professional settings':'Account settings'}</Badge><h1 className="mt-2 font-serif text-4xl font-bold">Settings</h1><p className="mt-2 text-sm text-[var(--text-secondary)]">Control your account, notifications, appearance, security, and workspace preferences.</p></div>{saved&&<span className="inline-flex items-center gap-2 rounded-xl bg-emerald-500/10 px-3 py-2 text-xs font-semibold text-emerald-400"><CheckCircle2 className="h-4 w-4"/>Saved</span>}</div>
 <div className="flex gap-1 overflow-x-auto border-b border-[var(--border-color)] pb-px">{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={`inline-flex shrink-0 items-center gap-2 border-b-2 px-4 py-3 text-xs font-semibold ${tab===t.id?'border-[var(--accent-blue)] text-[var(--accent-blue)]':'border-transparent text-[var(--text-secondary)]'}`}><t.icon className="h-4 w-4"/>{t.label}</button>)}</div>
 {tab==='profile'&&<Card variant="glass" className="p-6"><div className="flex items-center gap-4 border-b border-[var(--border-color)] pb-5"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[var(--accent-blue)]/10 text-lg font-bold text-[var(--accent-blue)]">{user?.initials||'LA'}</div><div><h2 className="font-serif text-xl font-bold">{user?.name||'LegalAI User'}</h2><p className="text-xs text-[var(--text-secondary)]">{user?.email||'—'}</p></div>{isLawyer&&<Badge variant={user?.verificationStatus==='VERIFIED'?'default':'warning'} className="ml-auto">{user?.verificationStatus==='VERIFIED'?'Verified':'Pending verification'}</Badge>}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Full name" value={user?.name||''}/><Field label="Email" value={user?.email||''}/>{isLawyer&&<><Field label="Bar Council" value={user?.barCouncil||'Not supplied'}/><Field label="Enrollment number" value={user?.barNumber||'Not supplied'}/></>}</div></Card>}
 {tab==='notifications'&&<div className="space-y-5"><Card variant="glass" className="p-6"><h2 className="font-serif text-xl font-bold">Notification channels</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{Object.entries(channels).map(([key,val])=><ToggleRow key={key} label={key==='email'?'Email notifications':key==='push'?'Push notifications':'In-app notifications'} value={val} onChange={v=>setChannels(c=>({...c,[key]:v}))}/>)}</div></Card><Card variant="glass" className="p-6"><h2 className="font-serif text-xl font-bold">Granular preferences</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{(isLawyer?lawyerPrefs:citizenPrefs).map(key=><ToggleRow key={key} label={labels[key]} value={prefs[key]??true} onChange={v=>setPrefs(p=>({...p,[key]:v}))}/>)}</div><Button onClick={save} className="mt-5"><Save className="mr-2 h-4 w-4"/>Save notification preferences</Button></Card></div>}
 {tab==='appearance'&&<Card variant="glass" className="p-6"><h2 className="font-serif text-xl font-bold">Appearance</h2><p className="mt-1 text-xs text-[var(--text-secondary)]">This preference is global and persists across Citizen and Lawyer pages.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{(['light','dark','system'] as Theme[]).map(t=><button key={t} onClick={()=>changeTheme(t)} className={`rounded-2xl border-2 p-5 text-left transition ${theme===t?'border-[var(--accent-blue)] bg-[var(--accent-blue)]/10':'border-[var(--border-color)] bg-[var(--bg-card)]'}`}><ThemeIcon theme={t}/><p className="mt-3 text-sm font-bold capitalize">{t}</p><p className="mt-1 text-[10px] text-[var(--text-muted)]">{t==='system'?'Follow device preference':t==='dark'?'Deep charcoal legal workspace':'Warm paper legal workspace'}</p></button>)}</div><div className="mt-6 rounded-xl bg-[var(--bg-card)] p-4"><div className="flex items-center gap-3"><Palette className="h-4 w-4 text-[var(--accent-gold)]"/><div><p className="text-xs font-semibold">Current theme</p><p className="text-[10px] text-[var(--text-muted)]">{theme}</p></div></div></div></Card>}
 {tab==='security'&&<div className="space-y-5"><Card variant="glass" className="p-6"><h2 className="font-serif text-xl font-bold">Password & security</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Current password" type="password" value=""/><Field label="New password" type="password" value=""/></div><Button className="mt-5" onClick={save}><Save className="mr-2 h-4 w-4"/>Update password</Button></Card><Card variant="glass" className="p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-serif text-xl font-bold">Two-factor authentication</h2><p className="mt-1 text-xs text-[var(--text-secondary)]">Frontend control for the future auth backend.</p></div><Badge variant="warning">Not enabled</Badge></div><Button variant="outline" className="mt-5">Enable 2FA</Button></Card><Card variant="glass" className="p-6"><h2 className="font-serif text-xl font-bold">Session control</h2><div className="mt-4 rounded-xl bg-[var(--bg-card)] p-4"><div className="flex items-center gap-3"><Clock3 className="h-4 w-4 text-emerald-400"/><div><p className="text-xs font-semibold">Current browser session</p><p className="text-[10px] text-[var(--text-muted)]">Protected local demo session</p></div><Badge className="ml-auto">Active</Badge></div></div><div className="mt-5 flex flex-wrap items-center gap-3"><LogoutButton compact/><Button variant="outline" size="sm" onClick={()=>{localStorage.removeItem('legalai-session');location.href='/';}}>Logout all devices</Button></div></Card></div>}
 {tab==='verification'&&isLawyer&&<Card variant="glass" className="p-6"><div className="flex items-start gap-4"><Shield className="h-6 w-6 text-purple-300"/><div><h2 className="font-serif text-xl font-bold">Professional verification</h2><p className="mt-1 text-xs leading-5 text-[var(--text-secondary)]">A real deployment should verify the enrollment number and identity against an authorized Bar Council/KYC source. The frontend cannot independently establish that a person is a real lawyer.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Info icon={FileCheck} label="Enrollment" value={user?.barNumber||'Missing'}/><Info icon={Briefcase} label="Bar Council" value={user?.barCouncil||'Missing'}/><Info icon={Shield} label="Status" value={user?.verificationStatus||'PENDING'}/></div><Button variant="outline" className="mt-5" onClick={()=>location.href='/lawyer/verification'}>Open verification workflow</Button></Card>}
 </div>;
}
function Field({label,value,type='text'}:{label:string;value:string;type?:string}){return <label className="block space-y-1.5"><span className="text-xs font-semibold">{label}</span><input type={type} defaultValue={value} className="w-full rounded-xl border border-[var(--input-border)] bg-[var(--input-bg)] px-4 py-2.5 text-sm"/></label>}
function ToggleRow({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between gap-4 rounded-xl border border-[var(--border-color)] bg-[var(--bg-card)] p-4"><span className="text-xs font-semibold">{label}</span><button type="button" onClick={()=>onChange(!value)} aria-pressed={value} className={`relative h-6 w-11 rounded-full transition ${value?'bg-[var(--accent-blue)]':'bg-[var(--bg-secondary)]'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value?'left-6':'left-1'}`}/></button></div>}
function Info({icon:Icon,label,value}:{icon:LucideIcon;label:string;value:string}){return <div className="rounded-xl bg-[var(--bg-card)] p-4"><Icon className="h-4 w-4 text-[var(--accent-blue)]"/><p className="mt-2 text-[10px] text-[var(--text-muted)]">{label}</p><p className="mt-1 text-xs font-semibold">{value}</p></div>}
