"""add lawyer escalation timeline and hearings

Revision ID: 94ace83410d2
Revises: b4fc0f2db86c
Create Date: 2026-08-26 21:15:48.617180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ace83410d2'
down_revision: Union[str, Sequence[str], None] = 'b4fc0f2db86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('practice_areas', sa.JSON(), nullable=False),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyer_profiles_location'), 'lawyer_profiles', ['location'], unique=False)
    op.create_index(op.f('ix_lawyer_profiles_user_id'), 'lawyer_profiles', ['user_id'], unique=True)
    op.create_table('case_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('FILED', 'NOTICE', 'REPLY', 'HEARING', 'ORDER', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('linked_document_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_events_case_id'), 'case_events', ['case_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_user_id', sa.String(length=36), nullable=False),
    sa.Column('lawyer_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='escalationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['citizen_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lawyer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_case_id'), 'escalations', ['case_id'], unique=False)
    op.create_index(op.f('ix_escalations_lawyer_user_id'), 'escalations', ['lawyer_user_id'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_table('hearings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('hearing_date', sa.DateTime(), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=True),
    sa.Column('pre_hearing_checklist', sa.JSON(), nullable=False),
    sa.Column('last_hearing_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'COMPLETED', name='hearingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hearings_case_id'), 'hearings', ['case_id'], unique=False)
    op.create_index(op.f('ix_hearings_hearing_date'), 'hearings', ['hearing_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hearings_hearing_date'), table_name='hearings')
    op.drop_index(op.f('ix_hearings_case_id'), table_name='hearings')
    op.drop_table('hearings')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_lawyer_user_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_case_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_case_events_case_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_lawyer_profiles_user_id'), table_name='lawyer_profiles')
    op.drop_index(op.f('ix_lawyer_profiles_location'), table_name='lawyer_profiles')
    op.drop_table('lawyer_profiles')
    # ### end Alembic commands ###
